apiVersion: v1
kind: Service
metadata:
  name: {{ include "ziwei.fullname" . }}-api
  labels:
    {{- include "ziwei.labels" . | nindent 4 }}
    app: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ziwei.selectorLabels" . | nindent 4 }}
    app: api
